### ISSUE TITLE
Question about login with github account password

### ISSUE THREAD

**Issue by xiaoheiwo** [tillson/git-hound#10]
Hello, when I use the script on my server device, GitHub requires me to enter a verification code for the new device login, but the tool cannot enter the verification code, which prevents me from using it。Is there a solution, or other login methods, thank you

**Comment by qiangyuefeng** [comment]
> 您好，当我在服务器设备上使用脚本时，GitHub要求我输入用于新设备登录的验证码，但是该工具无法输入验证码，这使我无法使用它。是否有解决方案或其他登录名方法，谢谢

我也是这个情况

**Comment by Ciyfly** [comment]
And why show login device is this  Device: Chrome on macOS

**Comment by tillson** [comment]
Check out https://github.com/tillson/git-hound/issues/7. 
For a temporary solution, you can head into github.go and change the user agent on line 40 to whatever browser you have on your computer.
