### ISSUE TITLE
git-hound: command not found

### ISSUE THREAD

**Issue by Sicmatr1x** [tillson/git-hound#13]
```
LI-iMAC:git-hound_1.2_Linux_x86_64 sic$ ls
LICENSE		README.md	config.yml	git-hound
LI-iMAC:git-hound_1.2_Linux_x86_64 sic$ git-hound --subdomain-file subdomains.txt
-bash: git-hound: command not found
```

Did I need add the git-hound to `.bash_profile`?

**Comment by tillson** [comment]
Yep, exactly. You can also run `./git-hound` as long as you're in the same directory as the `git-hound` file.

Thanks for the issue: I'll also update the README to make this a little more clear.
