### ISSUE TITLE
Unable to log into GitHub

### ISSUE THREAD

**Issue by joefizz** [tillson/git-hound#16]
**Describe the bug**
Using the latest binary (1.2.1) from an EC2 instance I am unable to login to GitHub.  

I have populated the ~/.githound/config.yml file with username and password.  I created a new GitHub account without 2FA (although I see 2FA is now supported).  I also tried proxying my brower through my EC2 instance and entering the emailed confirmation code but am still having the same problem.

**To Reproduce**
1. Populate config.ymal with credentials
2. run `echo "example.com" | git-hound`

**Expected behavior**
GitHub hunt begins

**Screenshots**
```
➜ 16:29 ~ %
➜ 16:29 ~ % echo "github.com" | git-hound
[*] Logged into GitHub as
[!] Unable to log into GitHub.
2020/05/12 16:30:09
➜ 16:30 ~ %
```

**Desktop (please complete the following information):**
 - OS: Kali
 - Version 1.2.1

**Comment by joefizz** [comment]
~/.githound/config.yml format (redacted)
```
# Required
# github_username: *********
# github_password: *********
```

**Comment by tillson** [comment]
Did you redact the username from `[*] Logged into GitHub as` or is it not showing up?

**Comment by joefizz** [comment]
no that is exactly how the error is displayed

________________________________

**Comment by tillson** [comment]
I see what your issue is: 
```
# Required
# github_username: *********
# github_password: *********
```
The `#` is a comment in YML, remove those and you'll be set

**Comment by joefizz** [comment]
ah of course.  i knew it'd be something at my end.  thank you!

________________________________
