### ISSUE TITLE
Help page thread default discrepancy

### ISSUE THREAD

**Issue by Harrison-Mitchell** [tillson/git-hound#19]
**Describe the bug**
`git-hound -h` has the line `--threads int     Threads to dig with (default 10). (default 20)`
So is the default 10 or 20?

**Additional context**
Using latest git release.

All the best :)

**Comment by tillson** [comment]
Thank you @Harrison-Mitchell! 20 is the correct number. Updated in https://github.com/tillson/git-hound/commit/16cc48d7736125e41fd48964b7b9df5ef0919bae.
