### ISSUE TITLE
Full dorks as queries

### ISSUE THREAD

**Issue by tillson** [tillson/git-hound#20]
**Is your feature request related to a problem? Please describe.**
GitHound users are currently limited on the complexity of queries sent into GitHound. This is because GitHound adds quotation marks around its queries (see https://github.com/tillson/git-hound/blob/master/internal/app/github.go#L177).

**Describe the solution you'd like**
We have two options:
1. Remove the quotation marks from the input entirely
2. Add a flag to remove them

**Additional context**
https://github.com/tillson/git-hound/blob/master/internal/app/github.go#L177

**Comment by tillson** [comment]
For readers, I would appreciate input on which solution works best for your workflow.

**Comment by tamjid1971** [comment]
![image](https://user-images.githubusercontent.com/45327979/82101573-a45bf080-972e-11ea-99a5-2c73b0587625.png)

**Comment by tamjid1971** [comment]
facing some problem for setup.

**Comment by tillson** [comment]
Hey @tamjid1971, 
It looks like you're trying to run the configuration file instead of the GitHound core program. When you write `./` in front of a filename, the shell interprets it as trying to run it. Try doing `./git-hound` instead. Was there something in the documentation that made that unclear?

Also, when reporting issues, please create a **new issue** instead of commenting on an old one so that people can quickly see relevant discussion. Thanks!

**Comment by githubtest611** [comment]
Hi @tillson, I'm currently using your script for a university project, are you planning to add query of type:
"filename:db.php" soon ? Or is it already available and I didn't see that ?

Thanks for you great work.

**Comment by tillson** [comment]
> Hi @tillson, I'm currently using your script for a university project, are you planning to add query of type:
> "filename:db.php" soon ? Or is it already available and I didn't see that ?
> 
> Thanks for you great work.

The idea here is to change githound's input so that users are able to use any GitHub search query/filter. (right now, `echo "test.com filename:db.php" | ./git-hound` translates to `"test.com filename:db.php"` in code search, which looks for the literal).

It sounds like this'll help you so I'll make the change.

**Comment by tillson** [comment]
Updated in master: see https://github.com/tillson/git-hound/commit/fda04b780c17df83bb853c42d4806f9dc3f15631 

Release coming soon–– my primary workstation's battery has died..
