### ISSUE TITLE
Add CSV/JSON output formats

### ISSUE THREAD

**Issue by marcelo321** [tillson/git-hound#29]
Hello,

i wanted to ask a quesiton since i just started using the tool and notice that when trying it i get way too many results of repositories i don't want.

Does it makes sense to pipe the command `echo "domain.com | git-hound | grep companyName`?

If we know the company's github profile, we can use that to only show results coming from their repositories?

I ask this because i don't know if it makes sense or not.

**Comment by tillson** [comment]
I like this idea. Your current workflow would work, but would be limited by GitHound's output format.

I think the best solution for this would be to enable GitHound to do different output formats (json, csv) so that you could do fine-tuned grepping

**Comment by realArcherL** [comment]
Is the repository dead? because it would be very helpful if the this feature could be added.

**Comment by tillson** [comment]
Will add this in the next week!

**Comment by tillson** [comment]
Fixed in 98d0e7a092fec6bd2d414db09e4b25661b5a674d
