### ISSUE TITLE
Documentation on config.yml

### ISSUE THREAD

**Issue by t94j0** [tillson/git-hound#3]
When following the setup guide, I ran into this issue:
`FileNotFoundError: [Errno 2] No such file or directory: 'config.yml'`

In the [setup] section of your README, you should add the file and file structure for config.yml.

[setup]: https://github.com/tillson/git-hound#setup

**Comment by tillson** [comment]
You make a very convincing argument, Mr. Harley. I will add this to our next sprint cycle, and you can expect it to ship in 90 days.

**Comment by attacker007** [comment]
Hi @tillson 

I've downloaded the released binary and extracted it. And then created config.yml and added the required inputs in that file.

```
nano ./config.yml

```

But when i tried to run the command to search for anything... I got this Error

```
[!] config.yml was not found.

```

**Comment by t94j0** [comment]
Make sure that your current working directory has the binary and config file in it. If you look at [the ReadConfig function][1], it says to add the CWD to the config path. I don't remember if that's the CWD of the binary hosted or the CWD you're working from. I would recommend trying 
 to add your config to `$HOME/.githound` and see if that works.

Best of luck

[1]: https://github.com/tillson/git-hound/blob/master/cmd/root.go#L118
