### ISSUE TITLE
Guide for Installation and Running

### ISSUE THREAD

**Issue by Molive-cell** [tillson/git-hound#31]
Dear Team, could you please provide a step by step guidelines of installing and running this application in Kali linux.

**Comment by MastinGood** [comment]
and also in windows when i try to run this **echo "\"tillsongalloway.com\"" | git-hound** it always says _'git-hound' is not recognized as an internal or external command,
operable program or batch file._

**Comment by tillson** [comment]
YouTube video coming this weekend, but in the meantime: 
1. Download latest version of GitHound for Linux systems at https://github.com/tillson/git-hound/releases (with `wget [url]` or from the web browser).
2. Decompress the download with `tar -xzf [filename]`. You may have to navigate to the Downloads folder with `cd` first.
3. `cd` into the now decompressed folder, and run `./git-hound` to test. You may need to create a `config.yml` file with the proper fields.

**Comment by amanchawla97** [comment]
even after putting config.yml it shows config.yml not found

**Comment by tillson** [comment]
@amanchawla97 Could you send a pic of `ls` in the directory that you're running githound from?

**Comment by amanchawla97** [comment]
Yes Sure please find the attached screenshot
![config](https://user-images.githubusercontent.com/29571175/84816754-0069ab80-b032-11ea-97bf-2f3b72ea5c65.png)

**Comment by tillson** [comment]
Can you show me the error when you try to run githound as well?

**Comment by amanchawla97** [comment]
![Screenshot 2020-06-17 07:49:05](https://user-images.githubusercontent.com/29571175/84826794-221e5f00-b041-11ea-8e05-97d2990102e5.png)

**Comment by JeremyCBrooks** [comment]
@amanchawla97 , how did you install git-hound? Your first screenshot shows the source code but no binary. Try putting your config.yml in ~/.githound.

**Comment by tillson** [comment]
For the `config.yml` issue, let's move discussion over to https://github.com/tillson/git-hound/issues/32.

**Comment by KongLynn** [comment]
> YouTube video coming this weekend, but in the meantime:
> 
> 1. Download latest version of GitHound for Linux systems at https://github.com/tillson/git-hound/releases (with `wget [url]` or from the web browser).
> 2. Decompress the download with `tar -xzf [filename]`. You may have to navigate to the Downloads folder with `cd` first.
> 3. `cd` into the now decompressed folder, and run `./git-hound` to test. You may need to create a `config.yml` file with the proper fields (see the README).
> 
> Let me know if you have any questions

Dear team：
  I installed the git-hound with 'git clone https://github.com/tillson/git-hound', and it always says 'git-hound' is not recognized as an internal or external command, which is same with @amanchawla97 .
could you please provide a step by step guidelines? Did I need to install golang first?

**Comment by tillson** [comment]
"git-hound" will only be recognized as a command if you add the binary to your $PATH variable. If it's not in your $PATH, you should run "./git-hound" while in the same directory as the binary.

**Comment by infosecjunky** [comment]
> ![Screenshot 2020-06-17 07:49:05](https://user-images.githubusercontent.com/29571175/84826794-221e5f00-b041-11ea-8e05-97d2990102e5.png)

Instead of this I have tried it like **echo "joor.com" | ./git-hound** if you have updated the user and password in the config.yml it will work.

**Comment by ashirali110** [comment]
I am using Linux (Redhat) Please help me to configure it I just want to install and configure it.

**Comment by ashirali110** [comment]
can someone send me the steps to do complete installation of git-hound.

**Comment by ashirali110** [comment]
Is it possible to integrate git-hound with Jenkins pipeline?

**Comment by infosecjunky** [comment]
> Is it possible to integrate git-hound with Jenkins pipeline?

Never tried it

**Comment by infosecjunky** [comment]
> @ashirali110
> 
> Try making a file called config.yml with the contents of this file: https://github.com/tillson/git-hound/blob/master/config.example.yml.
> 
> As for Jenkins, we don't have any integrations out of the box (although it is possible). I also am curious as to what use case you have for putting this in a Jenkins pipeline... I assume you're scanning new commits for secrets, in which case you may want to try https://github.com/trufflesecurity/trufflehog which is better at scanning single repositories/users/orgs for secrets (Githound is better for scanning all of GitHub when you don't have any guarantees about users or orgs) and has a Jenkins guide at https://github.com/trufflesecurity/trufflehog

Thanks for the information.

**Comment by ashirali110** [comment]
Hi @infosecjunky and @tillson  my config.yml is same as the repo you have send I want to ask that do I have to change the content in the config.yml file with my username and password?

**Comment by ashirali110** [comment]
My config.yml is present there in git-hound directory now what are the next steps can you please explain?

**Comment by infosecjunky** [comment]
> Hi @infosecjunky and @tillson my config.yml is same as the repo you have send I want to ask that do I have to change the content in the config.yml file with my username and password?

Yes you need to put your username and password for it to work.
<img width="971" alt="Screenshot 2022-05-26 at 14 32 50" src="https://user-images.githubusercontent.com/909969/170461406-283b99fe-fdae-46c5-a77b-df85a3f996eb.png">

**Comment by ashirali110** [comment]
@infosecjunky I have checked with that also but it did not work

**Comment by ashirali110** [comment]
If you have time can we have a call on teams or some other platform because I am not able to understand it how to do configurations.

**Comment by infosecjunky** [comment]
> 

can you share a screenshot of the error your getting

**Comment by ashirali110** [comment]
![image](https://user-images.githubusercontent.com/60770816/170463355-ad7a1157-a9c1-4940-adde-8286fe85bd25.png)

This is the same error getting after changing our username and password

**Comment by infosecjunky** [comment]
> ![image](https://user-images.githubusercontent.com/60770816/170463355-ad7a1157-a9c1-4940-adde-8286fe85bd25.png)
> 
> This is the same error getting after changing our username and password

Can you check if your files are in the right place like this
<img width="1088" alt="Screenshot 2022-05-26 at 14 48 57" src="https://user-images.githubusercontent.com/909969/170463978-9bae33b8-fc1a-4172-9ed6-36bdbdadad08.png">
?

**Comment by ashirali110** [comment]
@infosecjunky yes we have the same files which you have but still not able to do it :(

**Comment by infosecjunky** [comment]
> @infosecjunky yes we have the same files which you have but still not able to do it :(

is the user and password in double quotes?

**Comment by ashirali110** [comment]
@infosecjunky yes they have

**Comment by ashirali110** [comment]
do we have to give our bitbucket or github credentials?

**Comment by infosecjunky** [comment]
> do we have to give our bitbucket or github credentials?

I have tested only in github. Never tried gitbucket

**Comment by ashirali110** [comment]
But when we have installed git-hound we dont see any git-hound script but apart of that we have every file.

![image](https://user-images.githubusercontent.com/60770816/170468944-1e87fc75-7132-44e7-888f-e22c3c11eeef.png)

**Comment by ashirali110** [comment]
![image](https://user-images.githubusercontent.com/60770816/170469134-6a62a7c2-0811-4ff3-abfe-bea7196db0a3.png)
 we are having these files only

**Comment by infosecjunky** [comment]
> ![image](https://user-images.githubusercontent.com/60770816/170469134-6a62a7c2-0811-4ff3-abfe-bea7196db0a3.png) we are having these files only

Can you try to rename config.example.yml to something else. Maybe it might work

**Comment by ashirali110** [comment]
But I have one other folder name go in that i have that git-hound script I have moved it to git-hound is that the correct thing?

**Comment by ashirali110** [comment]
> > ![image](https://user-images.githubusercontent.com/60770816/170469134-6a62a7c2-0811-4ff3-abfe-bea7196db0a3.png) we are having these files only
> 
> Can you try to rename config.example.yml to something else. Maybe it might work

yes i will do it

**Comment by infosecjunky** [comment]
> But I have one other folder name go in that i have that git-hound script I have moved it to git-hound is that the correct thing?

can you remove everything. Download it fresh remane config.example.yml to config.yml and check?

**Comment by ashirali110** [comment]
From where we can download it fresh the best link do you have?

**Comment by infosecjunky** [comment]
> From where we can download it fresh the best link do you have?

the same link your using to download it https://github.com/tillson/git-hound.git

**Comment by infosecjunky** [comment]
I just noticed where is your git-hound executable? it should be in the same folder as config.yml to work as per my understaing

**Comment by ashirali110** [comment]
![image](https://user-images.githubusercontent.com/60770816/170472004-747ec33d-12c2-41cc-adb0-3300f3481134.png)

In this which we should download we are using linux Redhat

**Comment by infosecjunky** [comment]
> ![image](https://user-images.githubusercontent.com/60770816/170472004-747ec33d-12c2-41cc-adb0-3300f3481134.png)
> 
> In this which we should download we are using linux Redhat

if you have 64 bit then you should download 64 bit one

**Comment by ashirali110** [comment]
Thanks that error resolved now getting new error. Could you please guide on it?


![image](https://user-images.githubusercontent.com/60770816/170475080-7e364d8d-ebe4-487d-b849-da80f5003890.png)

**Comment by ashirali110** [comment]
![image](https://user-images.githubusercontent.com/60770816/170475662-54c8c755-5df3-491d-808e-fd2ccfa82702.png)

This is my config.yml file

**Comment by ashirali110** [comment]
I have put double quotation also and still not working.

**Comment by infosecjunky** [comment]
> I have put double quotation also and still not working.

echo "tillsongalloway.com" | ./git-hound try that

**Comment by ashirali110** [comment]
![image](https://user-images.githubusercontent.com/60770816/170481563-86126876-2b81-45ac-9b3e-98f31ecf6e0e.png)

**Comment by ashirali110** [comment]
getting this error

**Comment by infosecjunky** [comment]
> ![image](https://user-images.githubusercontent.com/60770816/170481563-86126876-2b81-45ac-9b3e-98f31ecf6e0e.png)

Your github account details is wrong thats why its unable to do it.

**Comment by ashirali110** [comment]
> echo "tillsongalloway.com" | ./git-hound try that

No luck we checked credentials are correct. Still getting the same error

**Comment by infosecjunky** [comment]
> > echo "tillsongalloway.com" | ./git-hound try that
> 
> No luck we checked credentials are correct. Still getting the same error

it says unable to login so thats the problem

**Comment by ashirali110** [comment]
Okay Thanks @infosecjunky but still not able to login :(

**Comment by Spraveensakthi** [comment]
Hi @infosecjunky , I am getting the below error while executing the command. please help to me solve the issue ASAP. I am giving the correct github user name and pwd.

![image](https://user-images.githubusercontent.com/89998727/170529653-0a72fad1-6318-470f-957a-99ba1584940d.png)

**Comment by Spraveensakthi** [comment]
Hi @infosecjunky , now we are successfully logged into the our github account.
![image](https://user-images.githubusercontent.com/89998727/170533270-fa20d01a-e82d-4aa6-987d-286814623b3a.png)

After this step, what we need to do?

**Comment by ashirali110** [comment]
I am also able to login yeahh

But after that what to do @infosecjunky ?

**Comment by infosecjunky** [comment]
> I am also able to login yeahh
> 
> But after that what to do @infosecjunky ?

what do you mean what to do? You know that the script does isnt it why your installing it?

**Comment by Spraveensakthi** [comment]
@infosecjunky we want to integrate the git-hound though jenkins script, is it possible to do it through jenkins pipeline?

**Comment by Spraveensakthi** [comment]
Hi @infosecjunky this command echo **"hanureddy022@gmail.com filename:search_test.go" | ./git-hound** helps to scan only the particular search_test.go file in the repo, but we want to scan all the files in the repository, for that what command should we use to do it?

**Comment by infosecjunky** [comment]
> @infosecjunky we want to integrate the git-hound though jenkins script, is it possible to do it through jenkins pipeline?

I have never tried this.

**Comment by infosecjunky** [comment]
> Hi @infosecjunky this command echo **"[hanureddy022@gmail.com](mailto:hanureddy022@gmail.com) filename:search_test.go" | ./git-hound** helps to scan only the particular search_test.go file in the repo, but we want to scan all the files in the repository, for that what command should we use to do it?

Im not part of support. Im just helping out to setup the script.

**Comment by a88xss** [comment]
Good afternoon, I have used two different GitHub accounts and I have the same authentication problem, in addition to my email no notification arrives to allow the use of the tool
![Captura desde 2022-06-06 12-46-33](https://user-images.githubusercontent.com/36142867/172216634-ff4342ab-0ce4-45fd-99c0-df1ca777d1c8.png)

**Comment by infosecjunky** [comment]
> Good afternoon, I have used two different GitHub accounts and I have the same authentication problem, in addition to my email no notification arrives to allow the use of the tool ![Captura desde 2022-06-06 12-46-33](https://user-images.githubusercontent.com/36142867/172216634-ff4342ab-0ce4-45fd-99c0-df1ca777d1c8.png)

your password must be wrong. It should be in between double quotes.

**Comment by tillson** [comment]
Created a Wiki for this.
