### ISSUE TITLE
"config.yml was not found" error

### ISSUE THREAD

**Issue by wifiuk** [tillson/git-hound#32]
what am I missing here?

Downloaded the latest binary.

![image](https://user-images.githubusercontent.com/3785545/84999647-5aa96000-b149-11ea-8d2e-dcab46980559.png)

**Comment by tillson** [comment]
A few people have reported this issue... I'm unable to reproduce it as a bug currently.

Does supplying the full config path with`--config-file` fix it? 
If not, what operating system are you on? I'll run a VM to see if that lets me replicate.

**Comment by wifiuk** [comment]
Happens on Linux and windows

**Comment by wifiuk** [comment]
Adding the path doesn't help either

**Comment by GeneralEG** [comment]
Same here for me

**Comment by shebi4** [comment]
same problem please patched this bug asap.

**Comment by wifiuk** [comment]
still have the same issue, totally different Linux system, using the lastest release from github.

**Comment by alexandrevvo** [comment]
> A few people have reported this issue... I'm unable to reproduce it as a bug currently.
> 
> Does supplying the full config path with`--config-file` fix it?
> If not, what operating system are you on? I'll run a VM to see if that lets me replicate.

Got it.. You must put login and password between quotes "" in the config.yml!

**Comment by ashhadali10** [comment]
not working same error

**Comment by elxandre** [comment]
@tillson Same error. You previously mentioned a YT video. Could you kindly post it here for us noobs to follow?

**Comment by 0xCC00FFEE** [comment]
Maybe we can simplify the process of loading the configuration file to only look it up at:
- The current root directory of the `Git-Hound` cloned repository.
- From the `--config-file` CLI flag.

If possible can anyone still facing this issue try the following diff in `cmd/root.go` and see if it solves the problem?
```
116,118c117,118
< 	viper.SetConfigName("config")
< 	viper.AddConfigPath("$HOME/.githound")
< 	viper.AddConfigPath(".")
---
> 	viper.SetConfigName("config.yml")
> 	viper.AddConfigPath("./")
```

**Note:** Changes are made based on the latest stable release v1.3

**Comment by tillson** [comment]
**SOLUTION**
I think this may be a case of a bad error message. @alexandrevvo seemed to figure out that the problem was that you need to put your username and password in quotation marks (see the updated https://github.com/tillson/git-hound/blob/master/config.example.yml).
If anyone is still having this issue even after doing quotation marks, I'd be interested to hear about it!

**Comment by sarahhumok7** [comment]
I'm having the same problem i using Windows 32 bit

**Comment by sarahhumok7** [comment]
![gttt666777ooi8](https://user-images.githubusercontent.com/99148825/152985457-0a74268d-35b0-4328-a29a-445360f58e9e.png)
I'm having this problem: No config file detected
I'm using Windows, I need help
