### ISSUE TITLE
not run githound 

### ISSUE THREAD

**Issue by sushantdhopat19** [tillson/git-hound#33]
i try to run githound but give this error

oot@kali:~/Desktop/git-hound# echo "\"tillsongalloway.com\"" | ./git-hound
[*] Logged into GitHub as sushantdhopat19
[!] Unable to log into GitHub.
2020/07/09 06:40:04

**Comment by tillson** [comment]
When you log into `github.com` with the same credentials you entered in the config, do you get any captive pages (2 factor authentication, verify new device, etc.)

**Comment by sushantdhopat19** [comment]
Thanks i solve this error already  i solve it with disabling the 2fa  .This work properly
Thanks

**Comment by kr0t3** [comment]
this cannot be possible in vps no graphic version right?
