### ISSUE TITLE
Gist search shows authenticity_token of GitHub itself.

### ISSUE THREAD

**Issue by Spacewalker2** [tillson/git-hound#35]
Hello,

thanks for the great tool! I'm using git-hound version 110.b18095e-1 of the blackarch repository like `git-hound --many-results --threads 100 <<< "example.com"`. If it is running the gist search then git-hound shows the authenticity_token of the GitHub page itself.

Bye

**Comment by Regala** [comment]
My results are also flooded with `authenticity_token` and `timestamp_secret`, don't know if it's from the same thing but makes really hard to see actual results/findings

**Comment by yayaainana** [comment]
me too

**Comment by schmiele** [comment]
same for me, using version from github on Debian

**Comment by Canon88** [comment]
me too

**Comment by tillson** [comment]
Could you send a screenshot of this?
