### ISSUE TITLE
config.yml was not found

### ISSUE THREAD

**Issue by welltest** [tillson/git-hound#38]
I created config.yml in ~/.githound/config.yml & /root/config.yml but facing this issue.
Even I tried --config-file but still not working

![2021-02-17 22_45_45-Kali](https://user-images.githubusercontent.com/7748482/108241727-25d72800-7172-11eb-859c-1419be60da85.png)

**Comment by elxandre** [comment]
same issue here

**Comment by elxandre** [comment]
@tillson Could you help?

**Comment by tillson** [comment]
Try putting quotes around your username and password in the config file. 
I just updated the example config to reflect this
