### ISSUE TITLE
git-hound: command not found

### ISSUE THREAD

**Issue by vansh1** [tillson/git-hound#42]
I am unable to run git-hound I spend my entire night trying to fix the issue, I tried everything I am using the latest version I have edited the config file and even tried downloading tar file manually then used tar -xzf file.tar.gz still i am unable to use 

please help me

**Comment by vansh1** [comment]
is anyone here to lookup my issue/

**Comment by tillson** [comment]
See https://github.com/tillson/git-hound/issues/13. You need to either run `./git-hound` in the directory where it is installed or add it to your command line path so it recognizes it as a command.

**Comment by vansh1** [comment]
how can i add it in my command line path so that my terminal recognizes it as command
