### ISSUE TITLE
unable to login into github

### ISSUE THREAD

**Issue by vansh1** [tillson/git-hound#43]
**Describe the bug**

root@kalibox:~/tools# ./git-hound --subdomain-file /home/box/https1.txt --dig-files --dig-commits --results-only
[!] Unable to log into GitHub.
2022/01/14 19:32:45 

# Required
my config file:
github_username: "user"
github_password: "pass"

**Expected behavior**
it should run for my given files
**Screenshots**

**Desktop (please complete the following information):**
ubuntu 20.04 latest one

**Additional context**

**Comment by AhmedBoulahsen** [comment]
i have the same bug

**Comment by AhmedBoulahsen** [comment]
# echo "hackerone.com" | git-hound
[*] Logged into GitHub as AhmedBoulahsen
[!] Unable to log into GitHub.
2022/01/14 23:51:58

**Comment by abernalneo** [comment]
Same issue here
[*] Logged into GitHub as xxxxx@xxxxxxxxxxxx.com
[!] Unable to log into GitHub.
2022/01/17 21:18:55

**Comment by abernalneo** [comment]
This helped me out:
echo "domain" | ./git-hound --config-file config.yml

**Comment by AhmedBoulahsen** [comment]
its not working with me i get this error

bash: ./git-hound: No such file or directory

**Comment by Canon88** [comment]
Same issue here

Mac

**Comment by zissosafe** [comment]
Same issue here, both with and without the --config-file option. Each time, I've copied user and pwd from the config file into the browser and there, the login works perfectly fine. git-hound ran once correctly (with the same config file), all the other times I got this error.

**Comment by vansh1** [comment]
i found a fix which may not work for all but just keep running git-hound continuously, keep doing this will finally help you that's how i solve that do that maximum time possible 
tip: keep internet fast or use vm

**Comment by Canon88** [comment]
There are many results：timestamp_secret、authenticity_token

**Comment by luizcorreia** [comment]
> I found what the problem is. In `GrabCSRFTokenBody` in github.go the regex is wrong. It searches for a string consisting of a-zA-z0-9+/=. But the tokens I'm getting contain a-zA-Z0-9-_. So I added - and _. My line 173 in github.go now looks like this:
> 
> ```
> re := regexp.MustCompile("authenticity_token\"\\svalue\\=\"([0-9A-z/=\\+\\-_]{32,})\"")
> ```
> 
> In my case it worked sometimes (~ 1 out of 10 times). That was when github generated a csrf_token that didn't contain the problematic characters.

Same here just getting `[!] Unable to log into GitHub.` , I have tryed the @supersache solution, but doesn't work for me.

**Comment by tillson** [comment]
Fixed in the latest commit!
