### ISSUE TITLE
No config file detected

### ISSUE THREAD

**Issue by sarahhumok7** [tillson/git-hound#45]
![vgggjjoooo](https://user-images.githubusercontent.com/99148825/152984892-fba9aab6-3b7b-40fc-88f0-d90f7b1f2308.png)
I'm having this problem: No config file detected
I'm using Windows, I need help

**Comment by ncsc-dev** [comment]
I'm having the same issue with Mac OS. Even if I point githound to the config file itself, it says: [!] config.yml was not found

command: ./git-hound --config-file <config-location>

**Comment by Tedixx** [comment]
I'm facing the same issue., using V1.7.2

**Comment by tillson** [comment]
> I'm having the same issue with Mac OS (ARM). Even if I point githound to the config file itself, it says: [!] config.yml was not found

`./git-hound --config-file` is not the correct command. Try `./git-hound --config-file config.yml`, assuming that the config.yml file is in your current directory.

**Comment by Tedixx** [comment]
Hi,

That gives the same result. The config file is in the same folder and is filled in just like the sample. Tried it on both Mac OS as Ubuntu 20.04. 

Kind regards,
@Tedixx
