### ISSUE TITLE
Unable to log into github 

### ISSUE THREAD

**Issue by Ajit1010** [tillson/git-hound#47]
My config.yaml file
![image](https://user-images.githubusercontent.com/86071727/158047299-4a2ad1a3-7d49-4684-905a-6da2449b1fdf.png)
![image](https://user-images.githubusercontent.com/86071727/158047326-a2ad8382-5714-436b-a0f1-c70c333f3e25.png)

**Comment by danielson-dotcom** [comment]
I have the same problem

**Comment by carr0t2** [comment]
I have the same problem

**Comment by basant-karki** [comment]
I have also the same problem

**Comment by waelahmed-dev** [comment]
Got same error
solved by putting github account email instead of username in config.yml file
for example:
github_username: "<github_account_email_here>"

**Comment by waelahmed-dev** [comment]
> Got same error solved by putting github account email instead of username in config.yml file for example: github_username: "[example@gmail.com](mailto:example@gmail.com)"

It really worked, bug after trying using the tool one more time I got the same error...
I think it should be updated to rely on github token like other tools, instead of username and password

**Comment by evanricafort** [comment]
> Got same error solved by putting github account email instead of username in config.yml file for example: github_username: "[example@gmail.com](mailto:example@gmail.com)"

this worked for me but after 2nd try, I got the same issue again.

**Comment by tillson** [comment]
This is fixed in the latest source code! Try cloning down the repo
