### ISSUE TITLE
[!] Unable to log into GitHub

### ISSUE THREAD

**Issue by Jim2g** [tillson/git-hound#49]
The problem is still unresolved,Sometimes there is a problem，sometimes is ok.

**Comment by a88xss** [comment]
Good afternoon, the same thing happens to me, I receive the error [!] Unable to log into GitHub.

I do not receive authorization mail or any notification about the use of the tool

**Comment by tillson** [comment]
For now, try compiling from the source code. There's a fix there that isn't in the downloadable binary. I'll push a new release that fixes it

**Comment by tillson** [comment]
Let me know if the new build (v1.4) works

**Comment by a88xss** [comment]
Good day, this new version 1.4 worked, after entering the respective 2FA that came to my email, I think the error that was being generated is regarding the management of 2FA or security checks

I clarify that I do not have any 2FA activated in my GitHub account but even so I received an email with a code.

A greeting and a thousand thanks for the help, if I find a reward I will let you know by intern.

A hug from Colombia
