### ISSUE TITLE
Error generating results 

### ISSUE THREAD

**Issue by ajaybalaji1119** [tillson/git-hound#56]
When I enter command echo "\"example.com\"" | git-hound It's throwing error dial tcp [2405:200:1607:2820:41::36]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

For most of result output it's showing like this.

**Comment by tillson** [comment]
This looks like it could be an issue on your end -- are you able to get to github.com directly? (or, has the problem resolved itself?)
