### ISSUE TITLE
No data searched

### ISSUE THREAD

**Issue by Canon88** [tillson/git-hound#58]
**Describe the bug**
I'm not sure it's a bug, but after I run git-hound it never "digs" into anything. I'm using v1.6.2。I have tried searching for many different keywords and it does not give me any information. It just returns "Finished"

**To Reproduce**
```
echo "xxxx" | ./git-hound --dig-files --dig-commits --many-results --threads 100
Enter your GitHub 2FA code: 473089
[*] Logged into GitHub as {xxxxxx}
[*] Searching 90 pages of results for 'xxxx'...
[*] Searching 2 pages of results for 'xxxx'...
Finished.
```

**Comment by skirge** [comment]
Same for me

**Comment by tillson** [comment]
I'm having trouble reproducing this

**Comment by Canon88** [comment]
> I'm having trouble reproducing this

I tried again and still couldn't search for data via git-hound.

Are you using it normally?

**Comment by Canon88** [comment]
> Are y'all running using the binary download or the source code? If you're using the binary, can you try using the source code?

I am using the binary run, I will try to run it with the source compiled.

**Comment by tillson** [comment]
Yep @Canon88

**Comment by tillson** [comment]
Do you have 2FA enabled on your account?
